% MATLAB Research Project Week 2 Assignment
% Ian Hay
% 2-1-2019

% Goal: Create a program that can plot the interference
% of a scatter point on a 2D area with color mapping
% for intensity for the following plots:
% magnitude, phase, real, and imaginary

e = 2.718;
PI = 3.14;

% x,y points of the scatter point
scatter_point_x = 0;
scatter_point_y = 2;
% cross section constant of the scatter point (how much the point displaces
% waves)
cross_section_constant = 0.3;
%initial e-field generated by the transmitter
E_field_start = 5;

grid off;

%meshgrid: creates grid of points for y,x
[x,y] = meshgrid(-2.5:0.01:2.5,0:0.01:4);

E = E_field_start .^ (j * (2 * PI) * x);

%E = cross_section_constant * (E_field_s .^ (j * (2 * PI) * (x - scatter_point_x)));
% ^ wrong

% e ^ -jkr (where r is the distance from the point to the scatterer)
% calculates the E-field displaced by the scatter point
Es = cross_section_constant * E .* (e .^ -(j * (2 * PI) * (sqrt(((x - scatter_point_x).^2) + ((y - scatter_point_y).^2)))));

%plots the magnitude subplot
subplot(2,2,1);
pcolor(abs(E+Es));
axis image, shading interp;
colorbar;

%plots the phase subplot
subplot(2,2,2);
pcolor(angle(E+Es));
axis image, shading interp;
colorbar;

%plots the real component of the E-field
subplot(2,2,3);
pcolor(real(E+Es));
axis image, shading interp;
colorbar;

%plots the imaginary component of the E-field
subplot(2,2,4);
pcolor(imag(E+Es));
axis image, shading interp;
colorbar;


